export const LIGHT_COLOR = "LIGHT";
export const ROOM_PAGE = "room-page";
// export const HOME_PAGE = ""
export const ACCOMODATIONS_SECTION = "accomodation";
export const ACCOMODATION = "accomodation";
export const RESORTS = "resorts";
export const HOLIDAY_STAYS = "holiday stays";
export const HOME = "home";
export const MAGAZINE = "magazine";
export const NAVBAR_WITH_BOTTOM_LINK = "navbar-with-bottom-links";
